### ISSUE TITLE
lavitで２度コンパイルするとlavitが固まってしまう

### ISSUE THREAD

**Issue by m-nozo** [lmntal/lavit#11]
LaViTで同じファイルを２度コンパイルするとエラーを吐いてLaViTが固まってしまう(動作を受け付けない)現象が起きました。

動作環境
・LaViT Version 2.8.7
・Windows8

エラー内容
java.lang.ClassCastException: javax.swing.text.DefaultStyledDocument cannot be cast to 

lavit.multiedit.coloring.LmnDocument
    at lavit.multiedit.coloring.LmnTextPane.getLMNDocument(Unknown Source)
    at lavit.multiedit.coloring.LmnTextPane$1.caretUpdate(Unknown Source)
    at javax.swing.text.JTextComponent.fireCaretUpdate(Unknown Source)
    at javax.swing.text.JTextComponent$MutableCaretEvent.fire(Unknown Source)
    at javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(Unknown Source)
    at javax.swing.text.DefaultCaret.fireStateChanged(Unknown Source)
    at javax.swing.text.DefaultCaret.changeCaretPosition(Unknown Source)
    at javax.swing.text.DefaultCaret.handleSetDot(Unknown Source)
    at javax.swing.text.DefaultCaret.setDot(Unknown Source)
    at javax.swing.text.DefaultCaret.setDot(Unknown Source)
    at javax.swing.text.DefaultCaret$Handler.propertyChange(Unknown Source)
    at java.beans.PropertyChangeSupport.fire(Unknown Source)
    at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
    at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
    at java.awt.Component.firePropertyChange(Unknown Source)
    at javax.swing.text.JTextComponent.setDocument(Unknown Source)
    at javax.swing.JTextPane.setDocument(Unknown Source)
    at lavit.multiedit.coloring.LmnTextPane.setText(Unknown Source)
    at lavit.multiedit.EditorPage.setText(Unknown Source)
    at lavit.editor.EditorPanel.createPage(Unknown Source)
    at lavit.editor.EditorPanel.openFile(Unknown Source)
    at lavit.editor.EditorButtonPanel$1.processFinished(Unknown Source)
    at lavit.runner.ProcessTask.dispatchProcessFinishEvent(Unknown Source)
    at lavit.runner.ProcessTask.access$600(Unknown Source)
    at lavit.runner.ProcessTask$MonitorThread.run(Unknown Source)

**Comment by k-ueda** [comment]
これは私も気づいています。単に２回コンパイルボタンを押してもたぶん
エラーは起きないですが、以下の操作をすると上記のエラーが出ます。
(1) あるファイルをコンパイルボタンでコンパイル
(2) できた　.il タブに現れる中間命令のどこかをマウスクリック
     （または編集）
(3) 再度元の .lmn ファイルを再度コンパイル
これで LaViT の全部ではないけど関連箇所が操作不能になります。

**Comment by k-ueda** [comment]
$B$3$l$O;d$b5$$E$$$F$$$^$9!#C1$K#22s%3%s%Q%$%k%\%?%s$r2!$7$F$b$?$V$s(B
$B%(%i!<$O5/$-$J$$$G$9$,!"0J2<$NA`:n$r$9$k$H>e5-$N%(%i!<$,=P$^$9!#(B
(1) $B$"$k%U%!%$%k$r%3%s%Q%$%k%\%?%s$G%3%s%Q%$%k(B
(2) $B$G$-$?!!(B.il $B%?%V$K8=$l$kCf4VL?Na$N$I$3$+$r%^%&%9%/%j%C%/(B
$B!J$^$?$OJT=8!K(B
(3) $B:FEY85$N(B .lmn $B%U%!%$%k$r:FEY%3%s%Q%$%k(B
$B$3$l$G(B LaViT $B$NA4It$G$O$J$$$1$I4XO"2U=j$,A`:nITG=$K$J$j$^$9!#(B

$B>eED(B $BOB5*!J(Bweb $B7PM3$GF~$l$k$H<+J,$K$O%a!<%k$,Ht$s$G$3$J$$$h$&(B
$B$J$N$G%a!<%k7PM3$G:F;n9T!K(B

**Comment by tsukimizake** [comment]
たぶん治ったためcloseします。(誰かもし同じエラーが出ることを発見したらre-openしてください)
