### ISSUE TITLE
ファイルオープン時の例外[2.8.6]

### ISSUE THREAD

**Issue by tamanyan** [lmntal/lavit#7]
LaViTでファイルツリー内のファイルをダブルクリックしてファイルを開こうとした際，例外が発生する場合がある．
（多くのタブを開いている際に起きやすいかもしれない．もしくは開いたファイルの累積数か）
以下，例外のトレース．

```
[13:45:28] java.lang.ClassCastException: javax.swing.text.DefaultStyledDocument cannot be cast to lavit.multiedit.coloring.LmnDocument
at lavit.multiedit.coloring.LmnTextPane.getLMNDocument(Unknown Source)
at lavit.multiedit.coloring.LmnTextPane$1.caretUpdate(Unknown Source)
at javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:407)
at javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4415)
at javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4437)
at javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:802)
at javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1277)
at javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1173)
at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1154)
at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1051)
at javax.swing.text.DefaultCaret$Handler.propertyChange(DefaultCaret.java:1852)
at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
at java.awt.Component.firePropertyChange(Component.java:8382)
at javax.swing.text.JTextComponent.setDocument(JTextComponent.java:453)
at javax.swing.JTextPane.setDocument(JTextPane.java:136)
at lavit.multiedit.coloring.LmnTextPane.setText(Unknown Source)
at lavit.multiedit.EditorPage.setText(Unknown Source)
at lavit.editor.EditorPanel.createPage(Unknown Source)
at lavit.editor.EditorPanel.openFile(Unknown Source)
at lavit.editor.EditorPanel$4.fileSelected(Unknown Source)
at extgui.fileview.FileTree.dispatchFileSelectedListener(Unknown Source)
at extgui.fileview.FileTree.onNodeClicked(Unknown Source)
at extgui.fileview.FileTree.access$100(Unknown Source)
at extgui.fileview.FileTree$2.mouseClicked(Unknown Source)
at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
at java.awt.Component.processMouseEvent(Component.java:6508)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
at java.awt.Component.processEvent(Component.java:6270)
at java.awt.Container.processEvent(Container.java:2229)
at java.awt.Component.dispatchEventImpl(Component.java:4861)
at java.awt.Container.dispatchEventImpl(Container.java:2287)
at java.awt.Component.dispatchEvent(Component.java:4687)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4501)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
at java.awt.Container.dispatchEventImpl(Container.java:2273)
at java.awt.Window.dispatchEventImpl(Window.java:2719)
at java.awt.Component.dispatchEvent(Component.java:4687)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
at java.awt.EventQueue.access$200(EventQueue.java:103)
at java.awt.EventQueue$3.run(EventQueue.java:694)
at java.awt.EventQueue$3.run(EventQueue.java:692)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.awt.EventQueue$4.run(EventQueue.java:708)
at java.awt.EventQueue$4.run(EventQueue.java:706)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by YuukiARIA** [comment]
StyledDocument の設定タイミングと EDT が絡んでそうですね。余裕があったら見ます。

**Comment by tsukimizake** [comment]
#11 と同じく、 #14 で解決しているはずなのでcloseしておきます。
